import MyContext from "@/Helper/Context";
import "./globals.css";

export const metadata = {
  title: "Mohammad Zaid",
  description: "Generated by Mohammad Zaid",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <MyContext>
          {children}
        </MyContext>
      </body>
    </html>
  );
}
